site_name: Computer Science Notes
copyright: Copyright &copy; 2022 UnoCS <a href="https://beian.miit.gov.cn/">京ICP备2022022008号</a>
repo_url: https://github.com/UnoCS/notes
repo_name: UnoCS/notes
edit_uri: ""
theme:
  name: material
  language: zh
  palette:
    primary: grey
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  plugins:
    - search
    - git-revision-date
    - git-revision-date-localized
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - admonition

nav:
    - 主页: index.md
    - 关于考试:
        - 前言: about_exam/introduction.md
        - 考试概要: about_exam/general-info.md
        - CSA&CSP: about_exam/CSA-vs-CSP.md
        - 选择题: about_exam/mcq-tips.md
        - 问答题: about_exam/free-response-tips.md
        - Java 速查: about_exam/java-quick-reference.md
    - Java基础:
        - 前言: language_basics/introduction.md
        - Java语言特点: language_basics/features.md
        - Java代码的基本元素: language_basics/elements.md
        - 变量和常量: language_basics/variables.md
        - 数据类型: language_basics/data_types.md
        - 类和对象: language_basics/classes_and_objects.md
        - 流程控制: language_basics/flow_controls.md
        - 错误: language_basics/errors.md
    - 程序设计和分析:
        - 前言: program_design_and_analysis/introduction.md
        - 软件开发的生命周期: program_design_and_analysis/software_dev_life_cycle.md
        - OOP程序设计: program_design_and_analysis/oop_design.md
        - 程序分析: program_design_and_analysis/program_analysis.md
    - 面向对象:
        - 前言: oop/introduction.md
        - 类和对象: oop/class_and_object.md
        - 继承和多态: oop/inheritance_and_polymorphism.md
    - 标准类:
        - 前言: standard_classes/introduction.md
        - Object类: standard_classes/object_class.md
        - String类: standard_classes/string_class.md
        - 封装类: standard_classes/wrapper_classes.md
        - Math类: standard_classes/math_class.md
    - 数据结构:
        - 前言: data_structure/introduction.md
        - 列表: data_structure/array.md
    - 算法:
        - 前言: algorithms/introduction.md
        - 排序: algorithms/sort.md
        - 搜索: algorithms/search.md
        - 递归: algorithms/recursion.md
    - 实验室:
        - 前言: labs/introduction.md
        - Magpie实验室: labs/magpie_lab.md
        - Elevens实验室: labs/elevens_lab.md
        - Picture实验室: labs/picture_lab.md
