site_name: Computer Science Notes
copyright: Copyright &copy; 2022 UnoCS
repo_url: https://github.com/UnoCS/notes
repo_name: UnoCS/notes
edit_uri: ""
theme:
  name: material
  language: zh
  palette:
    primary: grey
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - instant
    - tracking
    - tabs
    - sections
    - expand
    - top
    - search.highlight
    - search.share
  plugins:
    - search
    - git-revision-date
    - git-revision-date-localized
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - admonition

nav:
    - 主页: index.md
    - 关于考试:
        - 前言: about_exam/introduction.md
        - 考试概要: about_exam/general-info.md
        - CSA&CSP: about_exam/CSA-vs-CSP.md
        - 选择题: about_exam/mcq-tips.md
        - 问答题: about_exam/free-response-tips.md
        - Java 速查: about_exam/java-quick-reference.md
    - Java基础:
        - 前言: language_basics/introduction.md
        - Java语言特点: language_basics/features.md
        - Java代码的基本元素: language_basics/elements.md
    - 程序设计和分析:
        - 前言: program_design_and_analysis/introduction.md
    - 面向对象:
        - 前言: oop/introduction.md
    - 标准类:
        - 前言: standard_classes/introduction.md
    - 数据结构:
        - 前言: data_structure/introduction.md
    - 算法:
        - 前言: algorithms/introduction.md
    - 实验室:
        - 前言: labs/introduction.md
